source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EUActivityView_Example', :exclusive => true do
  pod 'EUActivityView', :path => '../'
end

target 'EUActivityView_Tests', :exclusive => true do
  pod 'EUActivityView', :path => '../'

  
end
